name: PR labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches: ['*']

jobs:
  check-labels:
    name: qe-approved|no-qe & docs-approved|no-docs
    runs-on: ubuntu-latest
    steps:
      - name: QE approval
        if: "!contains( github.event.pull_request.labels.*.name, 'qe-approved') && !contains( github.event.pull_request.labels.*.name, 'no-qe')"
        run: exit 1
      - name: Docs approval
        if: "!contains( github.event.pull_request.labels.*.name, 'docs-approved') && !contains( github.event.pull_request.labels.*.name, 'no-docs')"
        run: exit 1
